### ISSUE TITLE
Feedback on pts-with-genie

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#10]
Is there any way to save the profiled state from one run of a profile job and use it in a later job?  

Use case would be to profile the system, then make a configuration change wiht some other tool (for example NSO or Ansible), and then profile again and compare.  In this case, I expect it is 2 different genie scripts, one before and another after.  Can you store the "profile" and then load it up in a second script?  

Is there any way to access and leverage the python data structure of the profile in some other Python script?  A way to call the profile in a `my_script.py` file?

**Comment by lubnarasheed** [comment]
Yes absolutely, Genie has support to store the "profile" and then use/load it another script for comparison. I didn't mention it in the initial lab so as to not overwhelm the user with too many use cases but will add it now
