### ISSUE TITLE
Support running PyATS/Genie directly on host machine, not in container?

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#11]
The convenience or running the tools in a container is handy for a CICD pipeline, but when I'm learning about PyATS I'd like to install PyATS and Genie directly on my workstation in a virtual environment so I can leverage the other dev tools while working.  

Starting and working in the docker image interactively is a bit awkward and an extra hoop that I imagine several network engineers may struggle with as docker is not universally understood yet.  

Could we change the labs in the module to run PyATS and Genie directly in a venv on 10.10.20.20 (or locally on a personal dev workstation) rather than inside of a container?

**Comment by lubnarasheed** [comment]
Labs will be changed when Golden image is upgraded to Python3
