### ISSUE TITLE
Intro to pyATS lab --- pyats-ios-sample code with virl generate pyats

### ISSUE THREAD

**Issue by RunSi** [CiscoDevNet/pyats-labs#14]
Section 2.md instructs you to git clone the pyats-ios-sample code

Section 3.md instructs you to use virl generate pyats

The resulting testbed file has a topology that is inconsistent with the pyats-ios-sample code

topology:
  ios1:
    interfaces:
      GigabitEthernet0/1:
        ipv4: 10.10.10.1/24
        link: ios1-to-ios2
        type: ethernet
      GigabitEthernet0/0:
        ipv4: 10.255.0.38/16
        link: guest
        type: ethernet
  ios2:
    interfaces:
      GigabitEthernet0/1:
        ipv4: 10.10.10.2/24
        link: ios1-to-ios2
        type: ethernet
      GigabitEthernet0/0:
        ipv4: 10.255.0.39/16
        link: guest
        type: ethernet

The topology file includes GigabitEthernet0/0 on both routers.

The pyats-ios-sample code has the following lines

links = ios1.find_links(ios2)   -  this creates an unordered set of links from topology

self.parent.parameters['uut_link'] = links.pop()   - this adds the last item of the set to self.parent.parameters['uut_link'].  As this is an unordered set then this could either be link: guest or link ios1-to-ios2.  If it selects guest the the ping test case will fail.

There are two options I can see to overcome this

1. manually remove the topology for GigabitEthernet0/0 from default_testbed.yaml

2. change the pyats-ios-sample code

remove -----   
self.parent.parameters['uut_link'] = links.pop()  

add ----  
for y in links:
                     if y.name != 'guest':
                          self.parent.parameters['uut_link'] = y

**Comment by kecorbin** [comment]
Either of those are decent workarounds depending on how we want to handle this.  As the testbed is pretty static, I think we could also just hardcode an interface.  

**Relevant Docs**
https://pubhub.devnetcloud.com/media/pyats/docs/topology/usage.html#querying-topology

1. Hardcode 

```
ios.interfaces['GigabitEthernet0/1']
```

or even 

```
# loop through interfaces and find a interface that connects
# to a particular link
for intf in ios1:
    if  intf.link.name == 'ios1-to-ios2':
        self.parent.parameters['uut_link'] = y
```
@lubnarasheed  i'm also curious as to the behavior of find links.  I'm not sure why it's picking up that link

```
links = ios1.find_links(ios2)
```
What about the topology entry
```
GigabitEthernet0/0:
ipv4: 10.255.0.39/16
link: guest
type: ethernet
```
is causing pyATS to think thats a connection to the adjacent router?


docs seems to indicate (my) exected behavior

```
# find the links connecting n7k5 from n7k4
# using Device.find_links()
for link in n7k4.find_links(n7k5):
    print(repr(link))
# <Link rtr1-rtr2-2 at 0xf744ef8c>
# <Link rtr1-rtr2-1 at 0xf744d16c>
```

**Comment by kecorbin** [comment]
Here is my suggestion on this:  https://github.com/kecorbin/pyats-ios-sample/commit/481c5afd0eab4f2cca27ae03f1b1610166eb2a94

**Comment by lubnarasheed** [comment]
To be resolved in pull:
https://github.com/CiscoDevNet/pyats-ios-sample/pull/3
