### ISSUE TITLE
Feedback on intro-genie lab

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#6]
Here is an issue for feedback related to the Genie Labs.

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/3.md 

1. I don't see an `os: nxos` line in the generated testbed file.  Do I need to add it?  Is it needed?

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/1.md 

Add setup requirements of ensuring all Python pre-reqs are correct on the devbox before starting.  For example, virlutils needs to be 0.8.2 or higher, but the Sandbox (at least currently) is on a much older version.  

Perhaps consider including a requirements.txt and just doing a `sudo pip install -r requirements.txt` after cloning down the code.... 

Further, simply trying to upgarde virlutils in the default Python environment on 10.10.20.20 failed.. it reported success, but the 0.6.5 version was maintained.  I suggest starting the lab off with creating a venv for the labs, and installing virlutils, and other needed packages into it, rather than using the default environment included.  Better isolation and making sure the environment is exactly as needed.

**Comment by hpreston** [comment]
After running a test within the docker container, the lab says to "view the logs as discussed in intro-lab".  What is the practical way for the lab taker to view these files?  There is no web browser within the container that we are running in, and we have the users SSH to the 10.10.20.20 host so even if we exit from the container and use the DevBox, with the suggested method of ssh there is no way to open the files.  

Wouldn't it better to recommend users RDP to 10.10.20.20 and work from there.  Then they can actually open the files using Firefox on the devbox.  

Also... maybe add some more details about what to do once you open the logs, and how to use them in a useful fashion.  For the new to PyATS user, it can be a bit intimidating just to view the details without guidance.

**Comment by lubnarasheed** [comment]
Issues with executing the connect to device section were due to incorrect testbed YAML being generated by older version of virlutils - this is resolved by ensuring that the most up to date version of the package is pre-installed on the Sanbox

**Comment by lubnarasheed** [comment]
The DevNet sandbox instructions don't mention that RDP to 10.10.20.20 is possible, will check with Kevin if it is possible to do so. The automated Sandbox instruction email doesn't mention it either

**Comment by siming85** [comment]
RDP is a good option but this means it needs to be turned on in the ubuntu server - eg it needs to be created when the user requests for the lab, so after VPN they can just use RDP. If this is doable in the sandbox server let's do that.

w.r.t. docker - we can drop that and opt for:
- creating venv
- pip install

but this also requires python 3.4./3.5/3.6 pre-installed in the ubuntu. If you're using ubuntu 14 i think it does come pre-installed with python3.4, but without venv, so the sandbox server needs to be pre-built with ``apt-get install python3 python3.4-venv``, and we can update https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/4.md to do a venv creation.

thoughts? @hpreston

**Comment by hpreston** [comment]
@siming85 / @lubnarasheed  / @kecorbin We are working on updating the devbox in teh Sandbox to support both RDP and Py3.6.5.

**Comment by lubnarasheed** [comment]
Sandbox is still running with Python 2.7.5

[developer@devbox genie_learning_lab]$python
Python 2.7.5 (default, Jul 13 2018, 13:06:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

Closing this issue for now and continuing with using Docker containers.

When the Sandbox is prepped with Python 3.6.5 we can revisit the labs

**Comment by kecorbin** [comment]
Did you try ‘python3.6’
