### ISSUE TITLE
Notes on lab parsers-with-genie

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#7]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/parsers-with-genie/2.md

The link for "Genie Libs Parsers Availability" goes to the root of the https://github.com/CiscoTestAutomation/genieparser repo... doesn't actually list the parsers available.

**Comment by lubnarasheed** [comment]
Yes, we don't have a list of all the parsers available in Genie

For now the user could check the classes available in the repo

**Comment by hpreston** [comment]
@lubnarasheed got it.. then I suggest updating the learning lab to clear up the confusion... I went looking for a "list" and got stuck..

**Comment by hpreston** [comment]
On this step at the end... https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/parsers-with-genie/2.md 

You ask the user to 

> Examine the Python files show_bgp.py and show_platform.py. 

How should they examine?  Inside the container there is no `vi` or `nano`, and if we simply `cat` the file it displays a very long file that as a user I have no idea what to do with, or look for.  Is there any value in having the users look at the raw python for the parser?  If so you need to: 

* be explicit on how to open in something useful.  I'm not sure displaying the text with something like `cat` or `less` makes sense.  Having them look at the code via GitHub link, or by cloning locally and exploring with an IDE like Atom makes more sense
* Provide details about what to look at in the file, what line, and what to make not of.  Most network engineers are NOT strong Python developers... they won't get anything from skimming the code.

**Comment by lubnarasheed** [comment]
Great points, I think examining the code via GitHub link instead of using an editor/cat/less would be simpler at this point.

Will also add points as to what they should be looking for - MetaParser inheritance for schema, parser classes etc.
