### ISSUE TITLE
Feedback on triggers-verifications-with-genie

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#8]
Feedback on triggers lab

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/triggers-verifications-with-genie/2.md 

Question/comment on this lab... triggers make a ton of sense, and the idea of a "generic" trigger that isn't platform specific is awesome.. however the trigger being used (BGP) only seems to be supported on NX-OS.  Are most of the triggers single platform?  If this is a unique case, maybe use a different trigger that supports NX, XE, and XR to not give the wrong impression to the user.

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/triggers-verifications-with-genie/3.md

This is a really cool feature, and I liked going through it.  Would it be possible to setup the test to show a failure after the trigger?  Showing a failed test, and how to diagnose the "why" using the log output would be a very valuable addition to this lab.

**Comment by lubnarasheed** [comment]
Sure thing, I will add some triggers to the lab that can showcase failures as well and how to debug the log to diagnose why the trigger failed
