### ISSUE TITLE
Feedback on the scripts-with-genie

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#9]
Compilation of feedback on scripts lab

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/scripts-with-genie/1.md 

The links for the keywords don't work... appear to be internal Cisco links.  Are there public links that can be used?  

```
* Supported Keywords:
	- [Genie Robot Keywords](http://wwwin-pyats.cisco.com/cisco-shared/genie/latest/robot.html)
	- [PyATS Robot Keywords](http://wwwin-pyats.cisco.com/documentation/latest/robot.html)
	- [Unicon Robot Keywords](http://wwwin-pyats.cisco.com/cisco-shared/unicon/latest/robot.html)
```

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/scripts-with-genie/2.md 

It is not clear what the difference between this "script" is and the previous lab on triggers and verifications.  The only thing new that I can see is the

```
# Perform Checks: Verify number of BGP neighbors after trigger is the same as that before the trigger
verify number of bgp neighbors
    verify count "1" "bgp neighbors" on device "uut"
```

at the end, but why does this make it a "script"?

**Comment by hpreston** [comment]
https://github.com/CiscoDevNet/pyats-labs/blob/master/labs/scripts-with-genie/3.md

I'm not clear on the value of using "easypy" to run tests rather than just the previous method of "robot" and the scripts?  

Also, when I ran the `easypy genie_sample_job.py -testbed_file /genie_tests/default_testbed.yaml -html_logs` command a lot of data flew by the screen, and I was shocked because I didn't expect so much to come at me.  Why did it run?  What part of the script made all that happen?  

And on the archive... it took a minute for me to figure out it created and used a folder called `archive` to store a zip file.  Once I manually unzipped the archive and opened the `TaskLog.html` file I found the data to be quite interesting.  Have the users do that to see the value of what happened.

**Comment by hpreston** [comment]
I tried to run the example test that are referenced, but it didn't seem to work.  should this have given anything interesting?  

```
easypy demo1_harness_simple/demo1_harness_simple_job.py -testbed_file /genie_tests/default_testbed.yaml -html_logs
```

**Comment by lubnarasheed** [comment]
Updated Robot keywords links to point to external links

**Comment by siming85** [comment]
@hpreston maybe we overshot this one, let's backup a bit

robot is easy and great to get going with, but tbh there are tons of limitations with it. easypy gives the user a straight up python development experience, but that might not be for everyone. we thought it'll be best to actually show what the system is capable of - for advanced developers.

more so as a drop of pellet in the lake kind of idea, but not necessary a full tutorial.

**Comment by hpreston** [comment]
@siming85 The goal of the Learning Labs should be to give developers the information and details needed to get started using PyATS as quickly as possible.  The "introduction" labs can certainly expose users to what is possible, but rather than trying to provide a whirlwind tour of everything, it would be better to focus on 1 or 2 easy use cases that an engineer could use in their own work as soon as they complete the labs.  

While we'll have some advanced developers, and definitely want them to use PyATS and the labs, I believe the majority of our audience will be traditional network engineers who are learning NetDevOps skills and looking to fill the testing gap.
